name: Build and publish a Docker image to ghcr.io

on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

  # publish tags
  push:
    tags:
      - 'v*' # matches v1.0, v20.15.10

  # publish on pushes to the main branch (image tagged as "latest")
  #push:
  #  branches:
  #    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }} # it will be lowercased internally
          github_token: ${{ secrets.RELEASE_TOKEN }}
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag screenshot:$(date +%s)
